### ISSUE TITLE
Can't locate Net/DBus.pm in @INC

### ISSUE THREAD

**Issue by BrianZbr** [grifferz/dbus-scrobbler#1]
I'm on Ubuntu 14.04 and I noticed that the Banshee's scrobbler doesn't seem to be working, even though I have authorized it. I know nothing about dbus or perl but I tried executing this script. It gave me the following error: 

```
Can't locate Net/DBus.pm in @INC (you may need to install the Net::DBus module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /home/dowcet/Desktop/dbus-scrobbler line 8.
BEGIN failed--compilation aborted at /home/dowcet/Desktop/dbus-scrobbler line 8.
```

Any hints?

**Comment by grifferz** [comment]
You need to install `Net::DBus` perl module, which on Ubuntu…

```
⟫ apt search Net::DBus                                                   
Sorting... Done
Full Text Search... Done
libdesktop-notify-perl/trusty 0.03-1 all
  Perl module which communicates with the Desktop Notifications framework

libnet-dbus-glib-perl/trusty 0.33.0-1build3 amd64
  extension for the DBus GLib bindings

libnet-dbus-perl/trusty,now 1.0.0-2build1 amd64 [installed]
  Perl extension for the DBus bindings

```

…is the last one. So:

```
$ sudo apt install libnet-dbus-perl
```

**Comment by BrianZbr** [comment]
Thanks! That got me through several iterations of similar messages so I'll close this. 

I think the following would have covered all the dependencies I was missing (on a standard installation of Ubuntu 14.04): `sudo apt-get install libnet-dbus-perl libjson-perl libfile-slurp-perl`. I also did `libfile-read-perl` but I'm not sure if that one was necessary.
